/**
 * HEART Mock RAG Knowledge Base
 * Curated clinical guidelines for offline/demo use
 */

import { MedicalGuideline } from './types.js';

export const KNOWLEDGE_BASE: MedicalGuideline[] = [
  {
    id: 'nhs_elderly_care_2024',
    category: 'general_elderly_care',
    riskLevel: 'low',
    triggers: ['age > 65', 'routine monitoring', 'stable vitals'],
    recommendedActions: [
      'Annual comprehensive geriatric assessment',
      'Regular medication review',
      'Fall risk screening every 6 months',
      'Social isolation assessment',
    ],
    source: 'NHS_Elderly_Care_Pathway_2024',
    evidence: 'NHS England guidelines recommend proactive monitoring for all patients over 65 to prevent emergency admissions.',
    retrievalSource: 'mock',
  },
  {
    id: 'nice_falls_prevention',
    category: 'mobility_decline',
    riskLevel: 'moderate',
    triggers: ['step count decline > 20%', 'balance concerns', 'previous falls'],
    recommendedActions: [
      'Multifactorial fall risk assessment',
      'Home hazard assessment',
      'Exercise programme referral (strength and balance)',
      'Vision and hearing check',
      'Medication review for fall-risk drugs',
    ],
    source: 'NICE_CG161_Falls_Prevention',
    evidence: 'NICE CG161: Multifactorial interventions reduce fall rates by 24% in community-dwelling older adults.',
    retrievalSource: 'mock',
  },
  {
    id: 'kkm_warga_emas',
    category: 'general_elderly_care',
    riskLevel: 'low',
    triggers: ['Malaysian elderly patient', 'routine care', 'community monitoring'],
    recommendedActions: [
      'Regular health screening at Klinik Kesihatan',
      'Engage community health volunteers (KOSPEN)',
      'Ensure medication compliance through family support',
      'Refer to nearest Hospital for specialist assessment if needed',
    ],
    source: 'KKM_Warga_Emas_Guideline_2023',
    evidence: 'Malaysian Ministry of Health Warga Emas guidelines emphasize community-based care and family involvement.',
    retrievalSource: 'mock',
  },
  {
    id: 'nice_transition_care',
    category: 'cardiovascular_decline',
    riskLevel: 'high',
    triggers: ['heart rate deviation > 15%', 'activity decline > 30%', 'existing cardiac condition'],
    recommendedActions: [
      'Urgent GP/clinic assessment within 24-48 hours',
      'ECG and blood tests (troponin, BNP, renal function)',
      'Medication review and adjustment',
      'Consider hospital admission if acute presentation',
      'Cardiology referral if new symptoms',
    ],
    source: 'NICE_NG27_Transition_Care',
    evidence: 'NICE NG27: Patients with existing cardiac conditions showing decline patterns should be assessed urgently.',
    retrievalSource: 'mock',
  },
  {
    id: 'rcp_news2',
    category: 'acute_deterioration',
    riskLevel: 'critical',
    triggers: ['heart rate > 130 bpm', 'immobility + unresponsiveness', 'multi-system decline'],
    recommendedActions: [
      'Immediate clinical assessment',
      'Call emergency services (999) if life-threatening',
      'Continuous monitoring every 15 minutes',
      'Prepare for hospital transfer',
      'Notify next of kin immediately',
    ],
    source: 'RCP_NEWS2_Community',
    evidence: 'Royal College of Physicians NEWS2: Aggregate scoring identifies patients at risk of deterioration with 95% sensitivity.',
    retrievalSource: 'mock',
  },
  {
    id: 'nhs_emergency_protocol',
    category: 'emergency_response',
    riskLevel: 'critical',
    triggers: ['unresponsive > 24 hours', 'steps < 50 for 2+ days', 'cardiac arrest signs'],
    recommendedActions: [
      'CALL 999 immediately',
      'Alert nearest A&E department',
      'Notify all emergency contacts',
      'Prepare medication list for handover',
      'Do not delay for further assessment',
    ],
    source: 'NHS_Emergency_Protocol_2024',
    evidence: 'NHS Emergency Protocol: Immobility combined with unresponsiveness in elderly patients indicates potential acute medical crisis.',
    retrievalSource: 'mock',
  },
  {
    id: 'mems_malaysia',
    category: 'emergency_response',
    riskLevel: 'critical',
    triggers: ['Malaysian emergency context', 'critical vital signs', 'suspected cardiac event'],
    recommendedActions: [
      'Call MEMS 999 for ambulance dispatch',
      'Contact nearest Hospital Kerajaan A&E',
      'Family to prepare patient IC and medication list',
      'Keep patient comfortable and monitor until help arrives',
    ],
    source: 'MEMS_Malaysia_Emergency_Protocol',
    evidence: 'Malaysian Emergency Medical Services (MEMS) protocol for life-threatening emergencies in elderly patients.',
    retrievalSource: 'mock',
  },
  {
    id: 'nice_copd',
    category: 'respiratory_decline',
    riskLevel: 'high',
    triggers: ['COPD patient', 'activity decline', 'breathlessness indicators'],
    recommendedActions: [
      'Check oxygen saturation and spirometry',
      'Review COPD action plan',
      'Assess inhaler technique',
      'Consider oral steroids/antibiotics if exacerbation',
      'Pulmonary rehabilitation referral',
    ],
    source: 'NICE_NG115_COPD',
    evidence: 'NICE NG115: Early detection of COPD exacerbations through activity monitoring reduces hospitalization by 30%.',
    retrievalSource: 'mock',
  },
  {
    id: 'nice_diabetic_foot',
    category: 'diabetic_complications',
    riskLevel: 'moderate',
    triggers: ['diabetic patient', 'mobility changes', 'peripheral neuropathy'],
    recommendedActions: [
      'Diabetic foot assessment',
      'Review blood glucose control',
      'Check for ulceration or infection',
      'Podiatry referral if needed',
      'Patient education on foot care',
    ],
    source: 'NICE_NG19_Diabetic_Foot',
    evidence: 'NICE NG19: Early foot assessment in diabetic patients with mobility changes prevents 50% of amputations.',
    retrievalSource: 'mock',
  },
  {
    id: 'nice_af_management',
    category: 'cardiovascular_decline',
    riskLevel: 'high',
    triggers: ['atrial fibrillation', 'irregular heart rate', 'anticoagulation patient'],
    recommendedActions: [
      'Check pulse regularity and rate',
      'Review anticoagulation compliance (INR check)',
      'ECG if new symptoms or rate change',
      'Assess stroke risk (CHA2DS2-VASc)',
      'Cardiology review if poorly controlled',
    ],
    source: 'NICE_AF_Management_2021',
    evidence: 'NICE CG180: Regular monitoring of AF patients reduces stroke risk and hospital admissions.',
    retrievalSource: 'mock',
  },
];
